# Generated by Django 2.2.7 on 2019-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='DEFAULT TITLE', max_length=50)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('n_to', models.IntegerField(default=-1)),
                ('s_to', models.IntegerField(default=-1)),
                ('e_to', models.IntegerField(default=-1)),
                ('w_to', models.IntegerField(default=-1)),
                ('x', models.IntegerField(default=-1)),
                ('y', models.IntegerField(default=-1)),
            ],
        ),
    ]
